// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB07CEMFi2T5BUX6ZGz9vedMQLWJLxh22E',
    appId: '1:183795384114:web:c992615a6a70a3e4a9e12b',
    messagingSenderId: '183795384114',
    projectId: 'braintrain-62f15',
    authDomain: 'braintrain-62f15.firebaseapp.com',
    // storageBucket: 'braintrain-62f15.appspot.com',
    // measurementId: 'G-3FF0RT1R87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcT4fK9ap0S3eGEeCV_G5lzd4m4XXfoKQ',
    appId: '1:183795384114:android:d3c7cdd9f6203ebfa9e12b',
    messagingSenderId: '183795384114',
    projectId: 'braintrain-62f15',
    storageBucket: 'braintrain-62f15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe4NPf0tJwOqmN5I3myhDf4YJu0bukIjs',
    appId: '1:183795384114:ios:3f7b0a4cd338d57aa9e12b',
    messagingSenderId: '183795384114',
    projectId: 'braintrain-62f15',
    storageBucket: 'braintrain-62f15.appspot.com',
    iosBundleId: 'com.itbme.braintrainiv1.0.0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe4NPf0tJwOqmN5I3myhDf4YJu0bukIjs',
    appId: '1:183795384114:ios:8ea5381a77b486a7a9e12b',
    messagingSenderId: '183795384114',
    projectId: 'braintrain-62f15',
    storageBucket: 'braintrain-62f15.appspot.com',
    iosBundleId: 'com.example.brainTrainApp',
  );
}
